#  Import the numpy package under the name np 

In [1]:
import numpy as np

# Print the numpy version and the configuration 


In [2]:

from numpy import  __version__
print(__version__)

1.21.5


# Create a null vector of size 20 x=

In [4]:
x=np.zeros(20)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# How to find the memory size of any array 

In [50]:
x=np.random.randint(0,15,20)
np.size(x)

20

# How to get the documentation of the numpy add function from the command line? 

# Create a null vector of size 20 but the fifth value which is 1 

In [74]:
x=np.zeros(20)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Create a vector with values ranging from 10 to 68 

In [16]:
x=np.random.randint(10,68,10)
x

array([16, 36, 51, 13, 23, 55, 19, 44, 50, 65])

# Reverse a vector (first element becomes last) 

In [24]:
x=np.random.randint(10,30,10)
x

array([22, 17, 11, 20, 20, 16, 19, 19, 25, 27])

In [25]:
np.flip(x)

array([27, 25, 19, 19, 16, 20, 20, 11, 17, 22])

# Create a 3x3 matrix with values ranging from 0 to 10

In [6]:
np.random.randint(0,10,(3,3))

array([[8, 8, 0],
       [1, 3, 4],
       [3, 9, 9]])

# Find indices of non-zero elements from [0,2,1,0,4,0] 

In [75]:
np.indices([1,2,0,0,4,0])

array([], shape=(6, 1, 2, 0, 0, 4, 0), dtype=int32)

# Create a 3x3 identity matrix 

In [23]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create a 3x3x3 array with random values


In [7]:
y=np.random.randint(1,10,(3,3,3))
y

array([[[8, 3, 4],
        [4, 4, 4],
        [8, 1, 1]],

       [[8, 4, 2],
        [7, 2, 3],
        [1, 4, 3]],

       [[8, 4, 5],
        [1, 5, 1],
        [9, 1, 5]]])

#  Create a 10x10 array with random values and find the minimum and maximum values 

In [9]:
x=np.random.randint(1,100,(10,10))
x.min(),x.max()

(1, 99)

# Create a random vector of size 30 and find the mean value 

In [19]:
y=np.random.randint(1,10,30)
y.mean()

5.233333333333333

# Create a 2d array with 1 on the border and 0 inside 


In [76]:
x=np.ones((8,8))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

# How to add a border (filled with 0's) around an existing array? 

# What is the result of the following expression? 

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [77]:
n=5
a=np.zeros((n,n))
a
for i in range(n):
    for j in range(n):
        if(j==i-1):
            a[i,j]=i
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# Create a 8x8 matrix and fill it with a checkerboard pattern 


# Create a checkerboard 8x8 matrix using the tile function 


In [73]:
np.tile((0,1),(8,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

# Normalize a 5x5 random matrix 

# Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [26]:
x=np.random.randint(1,5,(5,3))
y=np.random.randint(1,5,(3,2))
x,y

(array([[2, 3, 4],
        [4, 1, 4],
        [1, 4, 2],
        [1, 2, 3],
        [1, 2, 4]]),
 array([[4, 2],
        [4, 1],
        [1, 4]]))

In [27]:
np.dot(x,y)

array([[24, 23],
       [24, 25],
       [22, 14],
       [15, 16],
       [16, 20]])

# Given a 1D array, negate all elements which are between 3 and 8, in place. 

# What is the output of the following script? 

In [ ]:
10

# Consider an integer vector Z, which of these expressions are legal? 

In [ ]:
Z<Z>Z

# What are the result of the following expressions? 


In [71]:
np.array(0) // np.array(0)


0

In [72]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

# How to find common values between two arrays? 


In [28]:
x=np.random.randint(1,50,(5,5))
y=np.random.randint(1,50,(5,5))
x,y

(array([[35, 12, 19, 41, 24],
        [23, 12, 47, 18, 33],
        [11, 28, 45,  2,  2],
        [38, 20,  6, 18,  1],
        [ 2, 22, 36, 34, 41]]),
 array([[24,  4,  5, 16, 22],
        [40, 39, 38, 15, 46],
        [39,  3, 20, 48, 18],
        [40, 22, 44,  2, 34],
        [ 4, 12, 13,  7, 31]]))

In [29]:
np.intersect1d(x,y)

array([ 2, 12, 18, 20, 22, 24, 34, 38])

# How to ignore all numpy warnings (not recommended)? 

In [ ]:
np.seterr(all="ignore")

# Is the following expressions true? 


In [ ]:
False

# How to get the dates of yesterday, today and tomorrow? 

In [61]:
import datetime
today = np.datetime64('today','D')
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
tomorrow= np.datetime64('today','D') + np.timedelta64(1,'D') 

print ("Today is:", today, "\n" "Yesterday is:", yesterday,"\n""Tomorrow is:",tomorrow,"\n")


Today is: 2023-02-26 
Yesterday is: 2023-02-25 
Tomorrow is: 2023-02-27 



# How to get all the dates corresponding to the month of July 2016? 


In [62]:
np.arange('2016-07', '2016-08',
                dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

# Extract the integer part of a random array of positive numbers using 4 different methods 

# Create a 5x5 matrix with row values ranging from 0 to 5 


In [49]:
x=np.random.randint(0,5,(5,5))
x

array([[3, 1, 0, 2, 3],
       [0, 3, 1, 0, 0],
       [0, 4, 0, 0, 3],
       [4, 3, 3, 0, 2],
       [2, 3, 1, 2, 1]])

# Create a vector of size 10 with values ranging from 0 to 1, both excluded 


In [63]:
np.random.rand(10)

array([0.43190901, 0.22848622, 0.64173325, 0.14551871, 0.73385974,
       0.53972056, 0.89428339, 0.06957559, 0.93436965, 0.06225897])

# Create a random vector of size 20 and sort it 


In [22]:
x=np.random.randint(10,30,20)
x
np.sort(x)

array([10, 11, 11, 12, 13, 14, 16, 17, 17, 21, 21, 22, 22, 24, 25, 26, 28,
       28, 29, 29])

# How to sum a small array faster than np.sum? 


In [67]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
print(a,"\n \n",b)
a+b

[[7 9 5]
 [5 5 3]
 [7 2 6]] 
 
 [[4 3 7]
 [3 6 6]
 [6 2 1]]


array([[11, 12, 12],
       [ 8, 11,  9],
       [13,  4,  7]])

# Consider two random array A and B, check if they are equal 


In [30]:
x=np.random.randint(1,10,(5,5))
y=np.random.randint(1,10,(5,5))
x,y

(array([[9, 6, 4, 3, 1],
        [2, 3, 4, 6, 3],
        [3, 1, 2, 4, 1],
        [8, 6, 1, 5, 5],
        [7, 2, 3, 1, 6]]),
 array([[1, 5, 1, 4, 2],
        [2, 1, 7, 8, 1],
        [5, 3, 1, 8, 7],
        [1, 2, 5, 8, 7],
        [4, 7, 8, 3, 1]]))

In [31]:
np.equal(x,y)

array([[False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

# Make an array immutable (read-only) 

In [48]:
a=np.random.randint(1,15,10)
print (a)
a.flags.writeable=False
a[5]=99

[ 7  9 11  9  8  4  1 11  2  6]


ValueError: assignment destination is read-only

# Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates 

# Create random vector of size 20 and replace the maximum value by 0 


In [40]:
x=np.random.randint(1,15,20)
print (x)
y=np.argmax(x)
print(y)
x[y]=0
x

[13  7 11  1  6  6 13  6  9  2  7 12  5  4  2  1 13  7  7  2]
0


array([ 0,  7, 11,  1,  6,  6, 13,  6,  9,  2,  7, 12,  5,  4,  2,  1, 13,
        7,  7,  2])

# Print the minimum and maximum representable value for each numpy scalar type 

# How to print all the values of an array? 


In [42]:
x=np.random.randint(1,10,(5,5))
print(x)

[[7 6 3 4 4]
 [3 4 9 4 5]
 [8 5 6 8 4]
 [8 1 2 6 1]
 [8 7 7 1 1]]


# How to convert a float (32 bits) array into an integer (32 bits) in place

In [44]:
x=np.random.randn(5,5)
print (x)
np.round(x)

[[ 0.65537947  0.56427327 -1.22432919  1.52818083 -0.74750555]
 [ 0.1047462  -0.344091    1.26414171  0.96036649  1.22431547]
 [ 0.49137511  1.38068393  2.66321576  1.16432375 -2.43570472]
 [ 1.18123093 -0.04318251  1.46817648 -1.07854598 -0.86347759]
 [ 0.02308497 -1.70842151  0.0535424  -2.22682227 -0.27423327]]


array([[ 1.,  1., -1.,  2., -1.],
       [ 0., -0.,  1.,  1.,  1.],
       [ 0.,  1.,  3.,  1., -2.],
       [ 1., -0.,  1., -1., -1.],
       [ 0., -2.,  0., -2., -0.]])

# How to randomly place p elements in a 2D array? 

# Subtract the mean of each row of a matrix 


In [79]:
x = np.random.randint(1,10,(3,3))
print (x)
y = x - x.mean(axis=1)
print(y)

[[5 5 2]
 [8 6 5]
 [1 5 7]]
[[ 1.         -1.33333333 -2.33333333]
 [ 4.         -0.33333333  0.66666667]
 [-3.         -1.33333333  2.66666667]]


# How to sort an array by the nth column? 

# How to tell if a given 2D array has null columns? 


In [69]:
a=np.random.randint(1,10,(3,3))
print (a)
np.isnan(a)

[[7 3 4]
 [3 7 4]
 [9 4 5]]


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

# Considering a four dimensions array, how to get sum over the last two axis at once? 

# How to get the diagonal of a dot product? 

In [68]:
a=np.random.randint(1,10,(5,5))
b=np.random.randint(1,10,(5,5))
a,b
np.dot(a,b)
np.diag(np.dot(a,b))

array([138, 105,  89,  87, 131])

# Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

# Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

# How to swap two rows of an array? 


In [46]:
x=np.random.randint(1,10,(4,4))
print (x)
np.roll(x,1,axis=0)

[[7 4 7 2]
 [3 1 7 3]
 [7 6 6 6]
 [8 9 9 5]]


array([[8, 9, 9, 5],
       [7, 4, 7, 2],
       [3, 1, 7, 3],
       [7, 6, 6, 6]])

# Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

# Compute a matrix rank 

In [70]:
a=np.random.randint(1,10,(5,5))
print (a)
np.linalg.matrix_rank(a)

[[9 3 2 7 1]
 [9 8 5 3 5]
 [8 5 3 8 1]
 [2 9 9 9 7]
 [3 2 2 7 8]]


5

# How to find the most frequent value in an array?


In [43]:
x=np.random.randint(1,10,15)
print (x)
np.bincount(x).argmax()

[2 6 6 7 5 1 1 9 2 8 7 9 3 3 9]


9

# How to get the n largest values of an array 

In [47]:
n=3
a=np.random.randint(1,15,10)
print (a)
b=np.sort(a)
print (b)
b[-n:]

[ 4  1 12  2  6  1  9  5  5  7]
[ 1  1  2  4  5  5  6  7  9 12]


array([ 7,  9, 12])